"""Add AI columns to LeadModel

Revision ID: 326e58024c7b
Revises: 39ab11ba43d0
Create Date: 2026-07-27 22:02:51.806401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326e58024c7b'
down_revision: Union[str, Sequence[str], None] = '39ab11ba43d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('ai_company_analysis', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_lead_score_details', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_outreach_email', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_conversation_summary', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_followup_recommendation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'ai_followup_recommendation')
    op.drop_column('leads', 'ai_conversation_summary')
    op.drop_column('leads', 'ai_outreach_email')
    op.drop_column('leads', 'ai_lead_score_details')
    op.drop_column('leads', 'ai_company_analysis')
    # ### end Alembic commands ###
