"""
AI Recommendation Model - persistent action items generated by Gemini pipelines.
"""
from sqlalchemy import Column, String, DateTime, ForeignKey, Float
from datetime import datetime, timezone
import uuid

from core.database import Base


def generate_uuid():
    return str(uuid.uuid4())


class AIRecommendation(Base):
    __tablename__ = "ai_recommendations"

    id = Column(String, primary_key=True, default=generate_uuid)
    organization_id = Column(String, ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)
    lead_id = Column(String, ForeignKey("leads.id", ondelete="SET NULL"), nullable=True, index=True)
    title = Column(String, nullable=False)
    reasoning = Column(String, nullable=False)
    confidence = Column(Float, default=0.85)
    priority = Column(String, default="High")  # High, Medium, Low
    recommended_action = Column(String, nullable=False)  # Outreach, Task, Call, Email
    status = Column(String, default="Pending")  # Pending, Approved, Dismissed, Completed
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
